resolver: lts-7.17
extra-deps:
- invertible-0.1.2
- web-inv-route-0.1.1
- postgresql-typed-0.5.0
flags:
  invertible:
    TypeCompose: false
    arrows: false
    hlist: false
    partial-isomorphisms: false
    piso: false
  web-inv-route:
    snap: false
    happstack: false
